// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammersBlog.Data.Concrete.EntityFramework.Contexts;

namespace ProgrammersBlog.Data.Migrations
{
    [DbContext(typeof(ProgrammersBlogContext))]
    [Migration("20220312110254_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CommentCount = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed orci mauris, luctus sit amet interdum ac, eleifend commodo tellus. Sed a justo et enim congue aliquet in eu ipsum. Donec efficitur purus ante, tempor ornare quam euismod id. Maecenas a felis sed mauris luctus accumsan. Sed dolor elit, pulvinar id nulla in, elementum mattis odio. Vestibulum lorem est, pharetra nec purus vel, sodales rhoncus odio. Nunc varius eleifend tortor, at consequat lectus placerat vitae. Vivamus quis porttitor felis. Morbi non iaculis massa, eget pharetra dui. Nam faucibus quam at elit vestibulum hendrerit. Aenean elementum augue sed porttitor accumsan.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(1681),
                            Date = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(779),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(2151),
                            Note = "C# 9.0 ce .Net 5 Yenilikleri",
                            SeoAuthor = "Sezer Sürücü",
                            SeoDescription = "C# 9.0 ce .Net 5 Yenilikleri ",
                            SeoTags = "C#, C# 9 ,.Net5 , .Net Framework , .Net Core",
                            Thumbnail = "Default.jpg",
                            Title = "C# 9.0 ce .Net 5 Yenilikleri",
                            UserId = 1,
                            ViewsCount = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CommentCount = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed orci mauris, luctus sit amet interdum ac, eleifend commodo tellus. Sed a justo et enim congue aliquet in eu ipsum. Donec efficitur purus ante, tempor ornare quam euismod id. Maecenas a felis sed mauris luctus accumsan. Sed dolor elit, pulvinar id nulla in, elementum mattis odio. Vestibulum lorem est, pharetra nec purus vel, sodales rhoncus odio. Nunc varius eleifend tortor, at consequat lectus placerat vitae. Vivamus quis porttitor felis. Morbi non iaculis massa, eget pharetra dui. Nam faucibus quam at elit vestibulum hendrerit. Aenean elementum augue sed porttitor accumsan.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(3191),
                            Date = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(3189),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(3193),
                            Note = "C++ 11 ve 19 Yenilikleri",
                            SeoAuthor = "Sezer Sürücü",
                            SeoDescription = "C++ 11 ve 19 Yenilikleri ",
                            SeoTags = "C++ 11 ve 19 Yenilikleri",
                            Thumbnail = "Default.jpg",
                            Title = "C++ 11 ve 19 Yenilikleri",
                            UserId = 1,
                            ViewsCount = 255
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CommentCount = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed orci mauris, luctus sit amet interdum ac, eleifend commodo tellus. Sed a justo et enim congue aliquet in eu ipsum. Donec efficitur purus ante, tempor ornare quam euismod id. Maecenas a felis sed mauris luctus accumsan. Sed dolor elit, pulvinar id nulla in, elementum mattis odio. Vestibulum lorem est, pharetra nec purus vel, sodales rhoncus odio. Nunc varius eleifend tortor, at consequat lectus placerat vitae. Vivamus quis porttitor felis. Morbi non iaculis massa, eget pharetra dui. Nam faucibus quam at elit vestibulum hendrerit. Aenean elementum augue sed porttitor accumsan. Suspendisse malesuada posuere ligula ac tincidunt.Donec dictum sagittis pulvinar.Donec ornare nec dui eget sagittis.Duis finibus eleifend lacus.Nulla tristique viverra suscipit.Ut lobortis lectus quis quam venenatis,nec sodales nunc laoreet.Maecenas hendrerit laoreet mi at fringilla.Nullam risus nulla,blandit sit amet vehicula vel",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(3199),
                            Date = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(3197),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 542, DateTimeKind.Local).AddTicks(3200),
                            Note = "C++ 11 ve 19 Yenilikleri",
                            SeoAuthor = "Sezer Sürücü",
                            SeoDescription = "Java Script S2019 ve S2020 Yenilikleri",
                            SeoTags = "Java Script S2019 ve S2020 Yenilikleri",
                            Thumbnail = "Default.jpg",
                            Title = " Java Script S2019 ve S2020 Yenilikleri",
                            UserId = 1,
                            ViewsCount = 10
                        });
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 545, DateTimeKind.Local).AddTicks(201),
                            Description = "C# Programlama dili ile ilgili en güncel bilgiler ",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 545, DateTimeKind.Local).AddTicks(254),
                            Name = "C#",
                            Note = "C# Blog Kategorisi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 545, DateTimeKind.Local).AddTicks(266),
                            Description = "C++ Programlama dili ile ilgili en güncel bilgiler ",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 545, DateTimeKind.Local).AddTicks(268),
                            Name = "C++",
                            Note = "C++ Blog Kategorisi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 545, DateTimeKind.Local).AddTicks(272),
                            Description = "Java Script Programlama dili ile ilgili en güncel bilgiler ",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 545, DateTimeKind.Local).AddTicks(273),
                            Name = "Java Script",
                            Note = "Java Script Blog Kategorisi"
                        });
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 546, DateTimeKind.Local).AddTicks(8953),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 546, DateTimeKind.Local).AddTicks(8965),
                            Note = "C# Makale Yorumu",
                            Text = "Suspendisse malesuada posuere ligula ac tincidunt. Donec dictum sagittis pulvinar. Donec ornare nec dui eget sagittis. Duis finibus eleifend lacus. Nulla tristique viverra suscipit. Ut lobortis lectus quis quam venenatis, nec sodales nunc laoreet. Maecenas hendrerit laoreet mi at fringilla. Nullam risus nulla, blandit sit amet vehicula vel, ullamcorper a elit. Aliquam aliquet vel elit vel imperdiet. Phasellus at nisi sed sapien volutpat commodo id a purus. Pellentesque rhoncus malesuada placerat. Ut metus felis, iaculis sed tristique sed, ultrices quis diam. Duis sit amet consequat ante. Curabitur nec magna rutrum, semper nisi at, tincidunt magna. Fusce sit amet neque bibendum, tempus urna et, feugiat diam."
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 546, DateTimeKind.Local).AddTicks(8977),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 546, DateTimeKind.Local).AddTicks(8978),
                            Note = "C++ Makale Yorumu",
                            Text = "Suspendisse malesuada posuere ligula ac tincidunt. Donec dictum sagittis pulvinar. Donec ornare nec dui eget sagittis. Duis finibus eleifend lacus. Nulla tristique viverra suscipit. Ut lobortis lectus quis quam venenatis, nec sodales nunc laoreet. Maecenas hendrerit laoreet mi at fringilla. Nullam risus nulla, blandit sit amet vehicula vel, ullamcorper a elit. Aliquam aliquet vel elit vel imperdiet. Phasellus at nisi sed sapien volutpat commodo id a purus. Pellentesque rhoncus malesuada placerat. Ut metus felis, iaculis sed tristique sed, ultrices quis diam. Duis sit amet consequat ante. Curabitur nec magna rutrum, semper nisi at, tincidunt magna. Fusce sit amet neque bibendum, tempus urna et, feugiat diam."
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 546, DateTimeKind.Local).AddTicks(8982),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 546, DateTimeKind.Local).AddTicks(8983),
                            Note = "Java Script Makale Yorumu",
                            Text = "Suspendisse malesuada posuere ligula ac tincidunt. Donec dictum sagittis pulvinar. Donec ornare nec dui eget sagittis. Duis finibus eleifend lacus. Nulla tristique viverra suscipit. Ut lobortis lectus quis quam venenatis, nec sodales nunc laoreet. Maecenas hendrerit laoreet mi at fringilla. Nullam risus nulla, blandit sit amet vehicula vel, ullamcorper a elit. Aliquam aliquet vel elit vel imperdiet. Phasellus at nisi sed sapien volutpat commodo id a purus. Pellentesque rhoncus malesuada placerat. Ut metus felis, iaculis sed tristique sed, ultrices quis diam. Duis sit amet consequat ante. Curabitur nec magna rutrum, semper nisi at, tincidunt magna. Fusce sit amet neque bibendum, tempus urna et, feugiat diam."
                        });
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 548, DateTimeKind.Local).AddTicks(4225),
                            Description = "Admin Rolü , Tüm Haklara Sahiptir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 548, DateTimeKind.Local).AddTicks(4241),
                            Name = "Admin",
                            Note = "Admin Rolüdür."
                        });
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(500)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 3, 12, 14, 2, 53, 560, DateTimeKind.Local).AddTicks(4748),
                            Description = "İlk Admin Kullanıcısı",
                            Email = "sezer@softekbilisim.com.tr",
                            FirstName = "Sezer",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sürücü",
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 3, 12, 14, 2, 53, 560, DateTimeKind.Local).AddTicks(4771),
                            Note = "Admin Kullanıcısı",
                            PasswordHash = new byte[] { 48, 49, 57, 50, 48, 50, 51, 97, 55, 98, 98, 100, 55, 51, 50, 53, 48, 53, 49, 54, 102, 48, 54, 57, 100, 102, 49, 56, 98, 53, 48, 48 },
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX4wVGjMQ37PaO4PdUVEAliSLi8-c2gJ1zvQ&usqp=CAU",
                            RoleId = 1,
                            UserName = "sezersurucu"
                        });
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Article", b =>
                {
                    b.HasOne("ProgrammersBlog.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgrammersBlog.Entities.Concrete.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("ProgrammersBlog.Entities.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.User", b =>
                {
                    b.HasOne("ProgrammersBlog.Entities.Concrete.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProgrammersBlog.Entities.Concrete.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
